name: flutter_intl_phone_field
description: A customized Flutter TextFormField to input international phone number along with country code.
version: 0.0.7
homepage: https://github.com/rvndsngwn/flutter_intl_phone_field
repository: https://github.com/rvndsngwn/flutter_intl_phone_field
issue_tracker: https://github.com/rvndsngwn/flutter_intl_phone_field/issues
documentation: https://github.com/rvndsngwn/flutter_intl_phone_field/blob/master/README.md
screenshots:
  - description: "Phone Number Picker"
    path: image-1.png
  - description: "Country Picker"
    path: image-2.png

topics:
  - flutter-intl-phone-field
  - intl-phone-field
  - international-phone-field
  - number-field
  - phone-field

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  test: ^1.24.9

flutter:
  assets:
    - assets/flags/
